[project]
id = "exsim-ipade"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
enable_confirmations = false
