// This file will be auto-generated by `supabase gen types typescript`
// Placeholder until Supabase project is connected

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          config: Record<string, unknown>;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          config?: Record<string, unknown>;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          config?: Record<string, unknown>;
          created_by?: string;
        };
        Relationships: [];
      };
      courses: {
        Row: {
          id: string;
          name: string;
          professor_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          professor_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          professor_id?: string;
        };
        Relationships: [];
      };
      worlds: {
        Row: {
          id: string;
          course_id: string;
          profile_id: string;
          name: string;
          current_period: number;
          status: "setup" | "active" | "paused" | "completed";
          seed: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          profile_id: string;
          name: string;
          current_period?: number;
          status?: "setup" | "active" | "paused" | "completed";
          seed?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          current_period?: number;
          status?: "setup" | "active" | "paused" | "completed";
        };
        Relationships: [];
      };
      teams: {
        Row: {
          id: string;
          world_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          world_id: string;
          name: string;
          created_at?: string;
        };
        Update: {
          name?: string;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role_in_team: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role_in_team?: string | null;
          created_at?: string;
        };
        Update: {
          role_in_team?: string | null;
        };
        Relationships: [];
      };
      periods: {
        Row: {
          id: string;
          world_id: string;
          period_number: number;
          status: "pending" | "decisions_open" | "processing" | "completed";
          deadline: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          world_id: string;
          period_number: number;
          status?: "pending" | "decisions_open" | "processing" | "completed";
          deadline?: string | null;
          created_at?: string;
        };
        Update: {
          period_number?: number;
          status?: "pending" | "decisions_open" | "processing" | "completed";
          deadline?: string | null;
        };
        Relationships: [];
      };
      decisions: {
        Row: {
          id: string;
          period_id: string;
          team_id: string;
          data: Record<string, unknown>;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          period_id: string;
          team_id: string;
          data?: Record<string, unknown>;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          data?: Record<string, unknown>;
          submitted_at?: string | null;
        };
        Relationships: [];
      };
      simulation_results: {
        Row: {
          id: string;
          period_id: string;
          team_id: string;
          state_snapshot: Record<string, unknown>;
          report: Record<string, unknown>;
          trace: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          period_id: string;
          team_id: string;
          state_snapshot?: Record<string, unknown>;
          report?: Record<string, unknown>;
          trace?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          state_snapshot?: Record<string, unknown>;
          report?: Record<string, unknown>;
          trace?: Record<string, unknown>;
        };
        Relationships: [];
      };
      simulation_jobs: {
        Row: {
          id: string;
          world_id: string;
          period_id: string;
          seed: number;
          status: string;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
          error: string | null;
        };
        Insert: {
          id?: string;
          world_id: string;
          period_id: string;
          seed: number;
          status?: string;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error?: string | null;
        };
        Update: {
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      world_status: "setup" | "active" | "paused" | "completed";
      period_status: "pending" | "decisions_open" | "processing" | "completed";
      user_role: "professor" | "participant";
    };
  };
}
