// This file will be auto-generated by `supabase gen types typescript`
// Placeholder until Supabase project is connected

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          config: Record<string, unknown>;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      courses: {
        Row: {
          id: string;
          name: string;
          professor_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["courses"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["courses"]["Insert"]>;
      };
      worlds: {
        Row: {
          id: string;
          course_id: string;
          profile_id: string;
          name: string;
          current_period: number;
          status: "setup" | "active" | "paused" | "completed";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["worlds"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["worlds"]["Insert"]>;
      };
      teams: {
        Row: {
          id: string;
          world_id: string;
          name: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["teams"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["teams"]["Insert"]>;
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role_in_team: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["team_members"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["team_members"]["Insert"]>;
      };
      periods: {
        Row: {
          id: string;
          world_id: string;
          period_number: number;
          status: "pending" | "decisions_open" | "processing" | "completed";
          deadline: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["periods"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["periods"]["Insert"]>;
      };
      decisions: {
        Row: {
          id: string;
          period_id: string;
          team_id: string;
          data: Record<string, unknown>;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["decisions"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["decisions"]["Insert"]>;
      };
      simulation_results: {
        Row: {
          id: string;
          period_id: string;
          team_id: string;
          state_snapshot: Record<string, unknown>;
          report: Record<string, unknown>;
          trace: Record<string, unknown>;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["simulation_results"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["simulation_results"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      world_status: "setup" | "active" | "paused" | "completed";
      period_status: "pending" | "decisions_open" | "processing" | "completed";
      user_role: "professor" | "participant";
    };
  };
}
